platform :ios, '12.0'
post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
  
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 12.0
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
            end
        end
    end
end

target 'ZenThrive-mobile' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'AppsFlyerFramework'
  pod 'FBSDKCoreKit', '17.0.0'
  pod 'SAMKeychain'
  pod 'AFNetworking'
  pod 'Masonry'
  pod 'lottie-ios'
  # Pods for ZenThrive-mobile

end
